DELETE http://localhost:8000/api/services/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3Njc5NTMxMTQsImV4cCI6MTc2Nzk1NjcxNCwicm9sZXMiOlsiUk9MRV9BSURBTlQiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJqZWFuQHRlc3QuY29tIn0.M7wp63MEzqatgy9M8NQ40RxA0FAxUS_L1qwH28FSXnL-N6EZTA_w-mgGP_poP-q85iJUE3sMbEdEHe6mrFhE6QN4EmOlg6qzdwjrqAwApvJR39lixveBsyHZDHrtjWwCjq_BddLGfMPzbWAIDoNW1VWwfi-rnssknHwTA82gVaFaszSYooNEn4tlLy_nfFpxn-AeAhr3utWO-lYVz2xU4ZPmObjmbQbLkAM2hWxN40p6zhw6ThJW2eq-At9V75LBdfjJoCG0gCxEz1gfGWZZal6TKBytnT34vtQ7BmMFJogKlh-qNbk1oWs-okHfMTirg0mtBolvKPdM3dRcBFzg6w
