DELETE http://localhost:8000/api/services/desinscription/9
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjgyMjYwNzcsImV4cCI6MTc2ODIyOTY3Nywicm9sZXMiOlsiUk9MRV9BSURBTlQiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJqZWFuQHRlc3QuY29tIn0.N71Kz2N6VJ4rbMD_IPHrbQ42Le_F-B5qQJh_3dLGfb3xCPMgIlueXcAxvlEyqi3m-dXXiLVR5pZy0objAhsTIPUmFxfNXoYaEjIGgRoYrkcjdlb2Y9NWXjzkboRKItoxztZWPizsH0EEeA5UUMNyffdvoQBYGW8Z8CGK0n3mf8JEuuMx56qcjSsmdvu7Gl9CzdFGKWIdwoA2yWnhjVMESP8gapMn4aHNfvXFCqsVYKpvuvpyK9IYGtAQ8rumXWPs3Zy4m7QEaqX_OT_aqFNvvITxjUeIpl-4gNPZ0-zTsmSfd7OuZH-vb1975ghhNoNE2DqCNo5u3mtZPHR03kHndA
