GET http://localhost:8000/api/services/4
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3Njc5NzQwNDEsImV4cCI6MTc2Nzk3NzY0MSwicm9sZXMiOlsiUk9MRV9BSURBTlQiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJqZWFuQHRlc3QuY29tIn0.T3XvA7-6tlkn5QwSnftfxWBaYOiXkXnGThSgIVsdSvltUoE0vgeuD8puMfKohCmOPoHOUKSxpGTLXoqOJfz6UK3LhXHOj50oLI3HT9KAjjUYDEmdRrkEeyxMo-Mxn1H0qqatnTKcN021KoUfn-rv41XUW7MVIUok3EgNGgfJYgAE6fVzlGFA1aCsh0Pgf0axexzM16Q_yV2l7xmhmsrJhgmmltOLYX4lLk6XPhHCSiLkJ10Oay-9rg5swj6zfuS_pgf6stEi-wInQ6K1WsAGLKTlN1Rkr306FnAZGZ3yfRzd5RRI-57Ofo2yETMjcnYqqqc0nMam0cZiKztebKDYww
Content-Type: application/json
