POST http://localhost:8000/api/services/map
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjgzMjA4MDMsImV4cCI6MTc2ODMyNDQwMywicm9sZXMiOlsiUk9MRV9BSURBTlQiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJqZWFuQHRlc3QuY29tIn0.l4n4cuTQaiVobxjEHUyei6l8a33Ro4H5X61MsZAN-NuCtuKTm6DKr8eqgwMxETF_QQKUWr1hqbsSC_ZcxL7H54tJloDvX0l2OWJP5YHNBEXh74js9QTU2h71AliDXDglX-Hw4V82obLdd5CWYzCm1kgqLtTf-jJ6Sc73RGNQZByhjWUS46ixwtNKko52lbp80adLbWGv5eTRHrfikINyV1VBK1Q0FdN8KElG4HZgxAk8VzzMhpqaEsjE66mkJOy1usu8gUDFzn-bySqjzqaH_-sCoaJCn_b4DK6a8Nt7bK9R6QByy7L20gxwFbAF6M_4H9XVPP5mwe5ioOHikOGspA

{
    "latitude": 45.360257464764,
    "longitude": 4.867289132457486,
    "rayon": 1000000
}
