GET http://localhost:8000/api/avantages/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjgyOTQ1MjYsImV4cCI6MTc2ODI5ODEyNiwicm9sZXMiOlsiUk9MRV9QUk8iLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJtaWNoZWxwcm9AdGVzdC5jb20ifQ.on9MePkGp3z23j6uxvIVrgjZ7ZePAU7HjFBoq_WC1J40JPoIg5jvPiQg6-j6XczeO7fAswMVKDnHo1JA1cgJfyky9jN9eaEN-3j8iSn02MXWKmGafTlTevBt0qi5bE78B7P0PsxFZ-4Lj-livrYtIostONPjRGudvQDN-zLjYD3E3SSrrExdO4igJpJ-OBgfmK_eXnh0Sz8MWapPc4fSypd2h2oLcuhYoRv3maH0Ls24qcl_JeaAGDHxF1BjG0Rjsb6-zY7fhFnGWUuMrdmkyYspfTdi-F5Nvepz67janaPXss7msYGbkywbWwDTyQeNEGlUxAmOtrud3dqGIdjfYA
