GET http://localhost:8000/api/avantages/approuves
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjgyOTMwMzksImV4cCI6MTc2ODI5NjYzOSwicm9sZXMiOlsiUk9MRV9BSURBTlQiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJqZWFuQHRlc3QuY29tIn0.aB37SXkg0gW_PqZVdqMAfugvVM4er40ULyLEjYJBLqR_IwmHsbAX-T6ZAEuobuzAmJfXf-j5JZRmUl6EegNcgwIh99iHrd8QizhBjnp3-pIqYN60_CMbHKAhTieaekUtuZRY1IOuvp_4w4Jf6lbCShDJLhcS0hlkcoQz0KvwUAO-k_ayQ58UhiQPTYNT_pTjE6EBuFYEETbeTqfOSsiW1DAJvOIkw5NStyNQyyBumVzAQAAvzjJBRUxWvS--tiU4dcUCeNR_6hNv4fldYqMG2DHVeBC2Zy3-m7L3TBqaTlMxaUn-HD23mdvozTDN7xd6gsUp7lYtLs3QqFqj2Vr63g
