GET http://localhost:8000/api/avantages/mes-avantages
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3Njg5MjQzNzcsImV4cCI6MTc2ODkyNzk3Nywicm9sZXMiOlsiUk9MRV9QUk8iLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJtaWNoZWxwcm9AdGVzdC5jb20iLCJpZCI6Mn0.u5q1G8JZ8wq_1GQWiHyOAcLRdbjiLnI4j1Z_zl7OWwW_WTWqh7L2g1FdhV3gmPYkzRK7Sa0vYhd2IZXRv7OBJIF8GDmshZfKN7gvWb2z2MT4-uetS_i6NUSJkvmrdImFOu8jQ6x_EqNpNxGkcmCAFi8Ktxfknes593q0_QqVJPzfjD8SMKw4JmEb_UXH04htdA8ShOll8IM0n1FHzWR6RGM_DyaxX-IS8f3Yq-fFeS6lnMUL0Hulnm9R6ctkFUxTRTp2IHT4L5ONE3V_iSYYhsxGsBR92prAEryfhW6RuHmcg5nKTKswD5ybF45SOybJads9Iw2VPHnc7h776ci_gQ
