GET http://localhost:8000/api/avantages/reclamer/6
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjgyOTkzMzQsImV4cCI6MTc2ODMwMjkzNCwicm9sZXMiOlsiUk9MRV9BSURBTlQiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJjbGF1ZGVAdGVzdC5jb20ifQ.nMV9VZ1tMbVg5tPrgcknvBB2wh4p3icx8R4jU9C1G-C0jbKDtU1595RfknwgooVDbnA17GXkdV03o9mY1c8aDgeFUNLfi8WgTzOv0lOYYqQJfq8NytKGpJwSijcG6gg8r82gdPCvXoyUPsIAGrxKPVX_mUIvTOQ9rHIgvWkhgmQRBZs14ynDxO8S8Gdir5s_QE3lVVgVRBKAXr-xqpJwYp4f5yqyaEVxK40CvylLlrsBuZEAxdkdi-51Z8U-Z_hnlhdeRM1zyewwTxF5BMqflI--rCNvbBCzsp1WBX5dOl7ci3Ctgm-KbAmClNauAx-JkTyI7ZzMP-VB_u6XZQMEhw
