POST http://localhost:8000/api/avantages/revoquer/6
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjgzMDkyOTQsImV4cCI6MTc2ODMxMjg5NCwicm9sZXMiOlsiUk9MRV9QUk8iLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJtaWNoZWxwcm9AdGVzdC5jb20ifQ.c8Mf2BIWsvwZCL4XRC5XZidrUOAjgiJuD_fW6SkHb-krFDbqTZtAxU_sTEeVViCmSj-I7uEHPHXJwOziwKaRtrgsOq-0GaSuvyX17PAPmuLxRkqd-r4ShwDpa518HzW4i10vuGjTq297ZHld_m4a3HqWEjl5yddDBJOgFZBr5khjOqf4VuechGT0YvcF4RiL5ehJ9HboJ0mDB9Jb_DmFBGJI3JlklwbCQRg9bAREVQriw7z0ceRu95jK3hKJ97x8p5WH4SrHvBNErSxM0wDac3SkzKQ9noTO-8K8vgGXq66wB2awTX7rfGuRzVMj2Qr9PDD_9d1ds3vb3R_WpbnlbA

{
  "aidantId": 11
}
