DELETE http://localhost:8000/api/avantages/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjgyOTc3NTMsImV4cCI6MTc2ODMwMTM1Mywicm9sZXMiOlsiUk9MRV9QUk8iLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJtaWNoZWxwcm9AdGVzdC5jb20ifQ.sgy7quO1gdRNt23FajNU2PRF_k2LFX1uOINx0rWZF5lLluEQ6uf9hAvNrecGPOvmwaNLquMEXuxaQ7sADgKxOX6_cRJb1QwPTQiaj1hI7ZuoVutO9Cej1OKkQ5Ek5Bg3CsnEEVwdMl8om4ltKZc1uF08QgF7Z1mJSiFPz1yWpG3brKPvEkTPjp_G1DOR6xfBhvcdMz7kWQbTSY1Hmy3BwWf0OLLbyu6bv92xkOqEyQvKKrLxTGxjskvu47UaJ_JzgUmfpFTydRIK6jeJHzXBI4iwxFsQ7_nC85RbhZ3xoXuFt4uVSuAfwdNDrtXHtIH1Ktq7pFOeBrmQH3a3mwTMHg
