POST http://localhost:8000/api/avantages/approuver/6
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjgyOTkwOTMsImV4cCI6MTc2ODMwMjY5Mywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQHRlc3QuY29tIn0.J8Zne0VzQ0nZzKmq_Dy5lD9FgRZO-RqZu7ZDZd_cbAdGf3H7p3p-MmA7b56WsKBsijOP4tho1kHya80ek9Y8dwpM_aNeLp9NjPUmeWKXRLndr88IqwjTckPk3uuNN_WvUmWLQmoj3-5hBrLqUQk2zlpQIKOqMIQIPz212BeeNGZvvDf7WHjuQdNrPJwGXE2FEeHO4W99w1XAVpnPa1SmRSNHeJLBRxQnpdUVSAqvSozydONEp3nk7EoiiMowl7nGksanp0cyFqVJtswlQRJLBUkYCNVe7erScFcMp-eI16DGd6R99WUfa3tbUUiTFScgiLJT2JL-OF3V6j3-MdGXuw
