### Supprimer un message (Jean supprime le message id=1)
DELETE http://localhost:8000/api/messages/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjgyOTE0NTAsImV4cCI6MTc2ODI5NTA1MCwicm9sZXMiOlsiUk9MRV9BSURBTlQiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJqZWFuQHRlc3QuY29tIn0.ND4aRTqs72WvV6FT9DLpow1k4DbywIP7w74Wf-QfpeGPaV7-kf3hqOxfEH_Enq2UN9l-RYAswU37-wRxURvMNjZeEZytS7V5TYmuCipWnZBYr9jotLEJx4bH0G9wLMYb8yjdeNpKNsrPcudnoAvG3nX-WpETR1-HwLfYHm5qfTr4fk4fKlDwnFlpRnFgKfNW3_TGukRsrA5x0Ay2AaulepxT6Q42D1ZuxhBx944uFia2-swjaHrQ0muFarXrqwHoFrS1QTOBaAC6-5wG2Rtt1mlAw2FWi9tGWHXkROR0SANiyKlwPFPm0KJA9fNVoWhuTrug1Xqq6eeUOYVRpkeWSQ
