POST http://localhost:8000/api/profile/adresses
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjkwMDUyNTgsImV4cCI6MTc2OTAwODg1OCwicm9sZXMiOlsiUk9MRV9QUk8iLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJtaWNoZWxwcm9AdGVzdC5jb20iLCJpZCI6Mn0.UhZmNcrVagISZ4D0fmKz2OIXIbdAnFkI78dshrQ9u8fde2_6z_JRY2I1DqNS-NQtU6qKBT5yykOtnewNdNrzozzA9koWPw_ABJfE9gPaNLu1N_Z_gdhFzNR4zjuRIYdzSli4m8ae0a1cuq9Cn_FDEzStejky0NukA3HtF_UCtFhROoDXzQARS2TpC40XUQtL-EN3GSimQc8gmeO0Smom1IV2Jpce1jmLMkv688v1lEkph1Vfwv4LQ6hI5JAj9et4ERGQIrDig4fVSenFlxsGKt799-mmL-256uoiOYk6Y9z2t1OC6gJgRADRpBW1RfoOolX8s7PbaFXmxML9JDXgXg

{
    "adresse": "10 rue des lilas"
}
