GET http://localhost:8000/api/taches
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjgyMzI4NzQsImV4cCI6MTc2ODIzNjQ3NCwicm9sZXMiOlsiUk9MRV9BSURBTlQiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJqZWFuQHRlc3QuY29tIn0.XcC_pvRtSIrq33GzP7rskX9f-njo5zk-Cz8z5iB7zvsgoqdi0kxpj0c-5qsVceHOdiLUtAvHZ4MmdKTm5ZsR20-Z0MCrgh6u0P6pSCW53GbTqgARbs3zAFYD22OqtY6kV1-2F6lFfKUqx9j3JZSI9s6Km1tNOl5J6ijlprm-Z0Jn7LzGLl3UyCv8NncZ8xAFvEVvpd4ZQ7_5yKoh-9z0UYR520U2PS7S2QfnoIOYy3e47TT6e8fI9yeAhixiKvXNFG6fUz51NJUD3g7htMrAhiznqdiMYKMIpJ1Cw-kWYslTIzTIMBlcm5pgN02lIYQYTL2Ya9ZyFEfMxwWna6XB_w
