POST http://localhost:8000/api/taches/taches_dun_groupe
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjgyMTE4ODYsImV4cCI6MTc2ODIxNTQ4Niwicm9sZXMiOlsiUk9MRV9BSURBTlQiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJhaWRhbnRAdGVzdC5jb20ifQ.equw3j_kay8GdcqC6C7XZquZleuGA37orX3RlY-YoEGUNuMMi0c4U5G3xECW-zHZWP7rqpFxqwaLjIX_LFLuujC6PHE60o9V_UFBbZcobCqGYciOdLAbLLYaJA66i-4h-Om2Xk9oU18chYit7iiF5lHXIxfE3n2aWCjdM8kJVQV5rlq_Nt_BvsO_DIy5JcxRoaHcJyYwxLSu57afgf3mFYeqOP6iVuj7RQrqT94NZvf5xBBoJs-1veT7nCi93-SC4xux173KiObt2HIyLk2Ibn08k0r2wB3nLxieAV6BQR4lAOnxWyEqbCP_PZmI7h6UuEOvwej0YKIgT2CP7j3qYw

{
    "id_groupe": 1
}
