POST http://localhost:8000/api/taches/taches_autres_membres
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjgzMTU2OTIsImV4cCI6MTc2ODMxOTI5Miwicm9sZXMiOlsiUk9MRV9BSURBTlQiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJqZWFuQHRlc3QuY29tIn0.vsiVkYKCaevFi43boxagiuD-giZI2oRNEzgZ6cATlle9G2eA74AXv7wFma5ER0kfPRj8bt5M9Z9LrsoVp3_w_bzKGokwOMDPhSKzuu3_4dL7IrRCubEcijZjADtvq13y6gKS8lpuuYWk7kwuNa38ifgzTNrDRlXkMhleGzVtxqFs_aQkY5n6Nz25pjL1wzqCzIrzdzObrO31cus0As6prf2AGvIsm12MpDs2wTSWtULohitnPYvdIKhJuCPcB5jZHWhbGtY-B2xA8A_r2sgJ0P89D3MEWG8kYyzxYM_0gbLe1GpWlUP_ZYLFL1LuJgtle3LA_FyvmuETHxx3fW215A


{
    "id_groupe": 2
}
