PUT http://localhost:8000/api/taches/3
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjgyMDgyOTAsImV4cCI6MTc2ODIxMTg5MCwicm9sZXMiOlsiUk9MRV9BSURBTlQiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJhaWRhbnRAdGVzdC5jb20ifQ.qvCYTgdQ4bbGKJNZNj4jwYmzNaTq9AWSL8WtTYEWN8msOkRMhKnFbXwJV-fyFgBJRKMyOfL-0_mlmTHYO1J8HOQZHGAXRsb7hey3XHf7FsXNbYmY3qzJXAnqkrxTdPVa92TBzhZdpwfsEq1Dsp3tXGyLWeFZlRkNouVKw6HalNyTRE0AnoWW7cZorkLShSBX-o_tYiII5lf5mkgPqAriexZxiz7_4ithgLvH93quw7XtQ5_-iEwrdIoJ-L0z9GtgcZz1lPxbscG276-mS5GAKSH5eR7zdHUIngaHxcW5u5p45h4PKhVNeTKalKLHhYG48LOK6pAWVYSWcJKTpadi7Q

{
    "nom": "Ménage Express (Nom modifié)"
}
