DELETE http://localhost:8000/api/taches/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjgyMTAyMTIsImV4cCI6MTc2ODIxMzgxMiwicm9sZXMiOlsiUk9MRV9BSURBTlQiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJhaWRhbnRAdGVzdC5jb20ifQ.HGmFpmcj8yxUivDfbxXJPfeeMcekZORkFtdnbsNunCUOObfsGXlqnDnf_xHEE0prniTujt_lVgelS7BngjF9qC1jQuLyt8ZTCnSNVwHTTBQi-ChabgODZBJC2uWYGDEsak2Pj33ys2UQTlHkQdIiSLbkuHBV0uq-y03wYLZdnOdcAd-pYks5GABYy6Pjh-4ZLk9z_Dbl9r89sTEam9DC3a9318oxpyT3zYqBC38FZgFRyyKW0NtgoKgme8FIX7yk-aL7XAJ388FlZ301MO4wASQozNz1Wjk27G7TCwK6httLjF85rfcU4OZoFY-Py7L4ZfReqmtjMYrcZqR2NFCKHQ
