GET http://localhost:8000/api/messages-groupe/groupe/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3Njg0MTA5MjEsImV4cCI6MTc2ODQxNDUyMSwicm9sZXMiOlsiUk9MRV9BSURBTlQiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJtYXJpZUB0ZXN0LmNvbSJ9.Kb4BtqkL_L7_SeuXmU_Jn5pOnaIa2gnpAZDsxDGd6qIoR5n4Hc7G6iPeZZpBi7ugB4M5pAsDumxsBEQWiNCK_4y0qsPDAXTGZ5weEdxhf76YUXXYYJ0BKW1O33yeVJ_6uZfgnvsf9VtQbjIBOBEWyJ13kxyjzblBX-NgRkoUit7h_6ExuOhvfg5UiDLK6ihSCgpwo6gVhRqCLCw7EyFNYYE1iRysaNRNMoyY5GtMKNFl_wZmMZ917SysvtrdXjXe8_3OWqxt6QpNmtqpMzRCXCNO6wCi6vl6iB9WXPmLYJEqgD43yLxNNUynDAvtf9x_Wf24e2OxUr1ZtBpAlyO9JQ
