POST http://localhost:8000/api/groupes/ajouter-membre/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjgzNzc3NjUsImV4cCI6MTc2ODM4MTM2NSwicm9sZXMiOlsiUk9MRV9BSURBTlQiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJqZWFuQHRlc3QuY29tIn0.wvRDLpYX6rPXR8HSGstnqxTgTYq21q44ElO0StTlChejc9FCUSFe4ZmKKFJeOOI6W9LwiZ2eCiJcUTb8P4MTBaitJCvGLwvfeESg68Mq3q5q1RoWzgpkRVhKWHNxTEltwQaYVvjm_d6gpRN4Magno2Qsq3fMN9RvfqY9WQAEsKb0V52J3RqCCA8DAAeooa5glbkjgvC84Q1QOyuZluyzjPtePJ86MllzDbx81F0VJKKlcCTdsL5LuS8PhvQeWaytw1UQ3f2uNQaG9vWJMzlqJUm4KBEkV12mleyjYC41ns9tk4QfJLp6zKrMbgvkb1bAUba8Aqd4IciPJFq-ulU8vQ


{
    "email": "claude@test.com"
}
