POST http://localhost:8000/api/groupes
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjgzNzkyOTEsImV4cCI6MTc2ODM4Mjg5MSwicm9sZXMiOlsiUk9MRV9BSURBTlQiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJjbGF1ZGVAdGVzdC5jb20ifQ.lIZrX9w9gu9U0tlzK823A0f8_0wwkzTsF-1FzL8asWRdWDtCrTSFf6h0o93tzOGsIZ3lIxb5IwBbPZkKCiKPmSSFTMLi4L27SI9lP-vwjLV4ywn5wsSdMQKQXjF6HOTN10FqdnAHQQGGYYqbTOVNulXXIvRcDVw4um8StInBKPeHdTsAkJknZFCVMgLlm0s1erE3hUM6gn30Vy2A-aTU5aYooCD8y1PTTPatiW-4Tfv-lnJMFXli_9K8rRt3E3lpfjpek4bDU7Y5EJb0CUz3FhQre9PzbOE9iwQMI16L0qGBoHW3XtAACZY2_N5uKmp780utS9zhnQkRTTSKLXGUWQ


{
"nom": "Famille Martin"
}
