POST http://localhost:8000/api/supprimer_compte/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3Njc5NDgzNjksImV4cCI6MTc2Nzk1MTk2OSwicm9sZXMiOlsiUk9MRV9QUk8iLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJwcm9AdGVzdC5jb20ifQ.Tg_wBVZxgMIpywKQKPxXXQT0irpYkswBzohk5tAUO4KYFQT75GxSscdwEsQ5dWsou2QoJTqg4HQ59vltszDS_3E6qq6OdRscR_2Rdde8nW8CYjyZtw5Xq5L_DPllE56e2T-FqAjDm9emikgNFa9M1p62bBCekAhrhAHas0D3qpVqXqXVUwp-MxTezpQnd1KSsGV97NrMsAErUCF0kjnyxAnnnRq-kh6b9dvhc6WudI6s5ijKh68B1O_N7Eo2DiFGjVrXYDOlFX94PX2dJC4G9TyHHZ6arzEsS0W4qOReWpXJkPTlaBFh94aBdwijbAet5Fs0anQjKWzVcuVl2Yi5Jg


{
    "password": "superMdp123"
}
