POST http://localhost:8000/api/password_modif/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3Njc5NTA0NTIsImV4cCI6MTc2Nzk1NDA1Miwicm9sZXMiOlsiUk9MRV9BSURBTlQiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJ0ZXN0M0BtYWlsLmNvbSJ9.wpX9SWYkUyd0ZjcNBIXhz1g-I0NnpPhdOVHFc7SDVDkvZyusetdAZ2Q4NQoAHRrueXpoA-yGsRjS1Zvm_NH-TfR5hgVw8gmx_SRwbAzfBoRG004sLwBkikJ9kJOwOPw1Eev7olukfPPB20U2UdNevjlxIJA-EmeC4BHRVsGjPCPr9YZwU-_tDilIpsAf4D5pckRUYycl1PuGcZn6ghIaMYMjkWC2DLGM9ipLZfs7sN-sOa7ieEf0G_C1CMlOar3xZUp07G3VvJLHGakm10ZlOJ7oNnjUUIVYa1HD3uA15I_0VYujrpmyk3W-bs9x6Dqi6_qFs9c3OGI67LfnL_iSEQ

{
    "old_password": "superMotDePasse123",
    "new_password": "nouveauMotDePasse456"
}
